in:
  type: bigquery_extract_files
  project: project
  json_keyfile: google-key.json
  #dataset: testdataset
  #table: testtable
  query: 'select a,b,c from testdataset.testtable'
  gcs_uri: gs://bucket/dir/csv-*
  temp_dataset: tempdataset
  temp_local_path: /tmp/test/data
  file_format: 'CSV'
  compression: 'GZIP'
  temp_schema_file_path: /tmp/test/schema/csv_schema.json
  decoders:
  - {type: gzip}
  parser:
    type: csv_with_schema_file
    default_timestamp_format: '%Y-%m-%d %H:%M:%S %z'
    schema_path: /tmp/test/schema/csv_schema.json
out: 
  type: mysql
  host: localhost
  user: user
  password: passwd
  port: 10315
  database: dbname
  table: test_table
  # https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html
  options: {connectTimeout: 0, enableQueryTimeouts: false, waitTimeout: 0}
  mode: insert_direct
  